"""Common base classes, context, registry, resolver, helpers, and errors."""

from handlers.common.base import CommonBaseHandler
from handlers.common.context import HandlerContext
from handlers.common.registry import BaseHandlerRegistry
from handlers.common.resolver import HandlerResolver
from handlers.common.errors import (
    HandlerError,
    HandlerNotFoundError,
    RegistrationError,
    ResolutionError,
    ConversionError,
    ValidationError,
)
from handlers.common.helpers import (
    to_number,
    to_bool,
    clean_dict,
    normalize_alignment,
    ALIGNMENT_MAP,
    DXA_PER_INCH,
    DXA_PER_CM,
    DXA_PER_PT,
    EMUS_PER_INCH,
    EMUS_PER_CM,
    EMUS_PER_PT,
    EMUS_PER_DXA,
    HALF_POINTS_PER_PT,
    EIGHTH_POINTS_PER_PT,
    dxa_to_pt,
    pt_to_dxa,
    inches_to_dxa,
    dxa_to_inches,
    cm_to_dxa,
    dxa_to_cm,
    emu_to_dxa,
    dxa_to_emu,
    emu_to_pt,
    pt_to_emu,
    inches_to_emu,
    emu_to_inches,
    half_points_to_pt,
    pt_to_half_points,
    eighth_points_to_pt,
    pt_to_eighth_points,
    bgr_to_hex,
    hex_to_bgr,
    hex_to_rgb,
    rgb_to_hex,
    normalize_hex_color,
)

__all__ = [
    "CommonBaseHandler",
    "HandlerContext",
    "BaseHandlerRegistry",
    "HandlerResolver",
    "HandlerError",
    "HandlerNotFoundError",
    "RegistrationError",
    "ResolutionError",
    "ConversionError",
    "ValidationError",
    "to_number",
    "to_bool",
    "clean_dict",
    "normalize_alignment",
    "ALIGNMENT_MAP",
    "DXA_PER_INCH",
    "DXA_PER_CM",
    "DXA_PER_PT",
    "EMUS_PER_INCH",
    "EMUS_PER_CM",
    "EMUS_PER_PT",
    "EMUS_PER_DXA",
    "HALF_POINTS_PER_PT",
    "EIGHTH_POINTS_PER_PT",
    "dxa_to_pt",
    "pt_to_dxa",
    "inches_to_dxa",
    "dxa_to_inches",
    "cm_to_dxa",
    "dxa_to_cm",
    "emu_to_dxa",
    "dxa_to_emu",
    "emu_to_pt",
    "pt_to_emu",
    "inches_to_emu",
    "emu_to_inches",
    "half_points_to_pt",
    "pt_to_half_points",
    "eighth_points_to_pt",
    "pt_to_eighth_points",
    "bgr_to_hex",
    "hex_to_bgr",
    "hex_to_rgb",
    "rgb_to_hex",
    "normalize_hex_color",
]
